import Link from "next/link";
import Head from "next/head";
import classes from "./Header.module.css";

const Header = () => {
  return (
    <>
      <Head>
        <title>bialek-k.pl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={classes.container}>
        <div className={classes.logo}>
          <p>KB</p>
        </div>
        <nav className={classes.nav}>
          <ul className={classes.navList}>
            <li>
              <Link href="/">
                <a>Start</a>
              </Link>
            </li>
            <li>
              <Link href="/blog">
                <a>Blog</a>
              </Link>
            </li>
            <li>
              <Link href="/contact">
                <a>Kontakt</a>
              </Link>
            </li>
          </ul>
        </nav>
      </header>
    </>
  );
};

export default Header;
